### ISSUE TITLE
CUDA memory issue

### ISSUE THREAD

**Issue by GDur** [msminhas93/DeepLabv3FineTuning#15]
Hello,

First off: Great work with this project, it is exceptionally cleanly written and structured imo!
It is nice to see that there is a tutorial, the full code on github with clean _and_ working instructions. (It is working using the CPU for me) :)

Is there a way to make pytorch reserve less RAM?
In another post someone talked about a active variable in the session which seems to use too much memory:
https://discuss.pytorch.org/t/how-does-reserved-in-total-by-pytorch-work/70172/2

Could this be the case? (I am not an Python expert)

Here's the issue:
```cmd
\DeepLabv3FineTuning-master> python main.py --data-directory CrackForest --exp_directory CFExp --epochs 1
Epoch 1/1

  0%|                                                                                           | 0/24 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main()
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 53, in main
    _ = train_model(model,
  File "C:\Users\gdurm\Downloads\DeepLabv3FineTuning-master\DeepLabv3FineTuning-master\trainer.py", line 49, in train_model
    outputs = model(inputs)
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\torchvision\models\segmentation\_utils.py", line 19, in forward
    features = self.backbone(x)
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\torchvision\models\_utils.py", line 63, in forward
    x = module(x)
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\torchvision\models\resnet.py", line 133, in forward
    out = self.bn3(out)
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\torch\nn\modules\batchnorm.py", line 135, in forward
    return F.batch_norm(
  File "C:\tools\Anaconda3\envs\deeplabfinetuning\lib\site-packages\torch\nn\functional.py", line 2146, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 38.00 MiB (GPU 0; 2.00 GiB total capacity; 1.05 GiB already allocated; 11.44 MiB free; 1.10 GiB reserved in total by PyTorch)```

**Comment by msminhas93** [comment]
Thank you. For the CUDA error, you won't be able to train this model with 2 GB GPU memory. It isn't sufficient to fit the model. Try using a 12 GB GPU (maybe Google Colab?).

**Comment by hanhern** [comment]
Hi, would a 8 GB GPU be sufficient?
