### ISSUE TITLE
Expected more than 1 value per channel when training

### ISSUE THREAD

**Issue by bemoregt** [msminhas93/DeepLabv3FineTuning#5]
Hi, @msminhas93 

I met this error when run with my data.

ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])

What's wrong to me?

Thanks
Best,
@bemoregt.

**Comment by msminhas93** [comment]
Could you please share more details? What is the input shape? Are you using the code without any modifications? A screenshot of the error is often better.

**Comment by bemoregt** [comment]
Hi, @msminhas93 

What is the input shape? 
>> Images: 256x256 RGB & no alpha channel Images.
>> Masks: 256x256 grayscale & no alpha channel Images.

Are you using the code without any modifications? 
>> Yes I am.

A screenshot of the error is often better.
>> 
macPro:DeepLabv3FineTuning o2$ 
macPro:DeepLabv3FineTuning o2$ python3 main.py CrackForest/ .
Epoch 1/25
----------
 83%|████████████████████████████████████████████████▎         | 5/6 [03:09<00:37, 37.83s/it]Traceback (most recent call last):
  File "main.py", line 53, in <module>
    optimizer, bpath=bpath, metrics=metrics, num_epochs=epochs)
  File "/Users/o2/DeepLabv3FineTuning/trainer.py", line 47, in train_model
    outputs = model(inputs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torchvision/models/segmentation/_utils.py", line 24, in forward
    x = self.classifier(x)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/o2/DeepLabv3FineTuning/models/segmentation/deeplabv3.py", line 92, in forward
    res.append(conv(x))
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/o2/DeepLabv3FineTuning/models/segmentation/deeplabv3.py", line 61, in forward
    x = super(ASPPPooling, self).forward(x)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 107, in forward
    exponential_average_factor, self.eps)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/functional.py", line 1666, in batch_norm
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])
 83%|████████████████████████████████████████████████▎         | 5/6 [03:14<00:38, 38.85s/it]
macPro:DeepLabv3FineTuning o2$ 

Thanks.
Best,
@bemoregt.

**Comment by nick-nagaraj** [comment]
@bemoregt I encountered the same issue. What worked for me was to keep the batch size as 4. Batch sizes of 2 and 1 caused this problem. If you are running out of memory, what you can try is to decrease the resolution of the images and masks. 480x320 worked for me.

**Comment by tangwentlw** [comment]
@nick-nagaraj I am still facing the same error as @bemoregt I am using the code without modification and the image size is of 480*320*3(channels) RGB images. The mask is of size 480*320 binary image with only 0 and 255. The error is as follow:

(torch) D:\jyp\ICP-SHM-P1\DeepLabv3_torch>python main.py "D:\jyp\ICP-SHM-P1\DeepLabv3_torch\IPC_Crack" "D:\jyp\ICP-SHM-P1\DeepLabv3_torch\IPC_Crack\exp"
Epoch 1/25
----------
 99%|███████████████████████████████████████████████████████████████████████████████▎| 124/125 [02:17<00:01,  1.11s/it]
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "main.py", line 53, in main
    trained_model = train_model(model, criterion, dataloaders,
  File "D:\jyp\ICP-SHM-P1\DeepLabv3_torch\trainer.py", line 47, in train_model
    outputs = model(inputs)
  File "C:\Users\tangw\Anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\tangw\Anaconda3\envs\torch\lib\site-packages\torchvision\models\segmentation\_utils.py", line 24, in forward
    x = self.classifier(x)
  File "C:\Users\tangw\Anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\tangw\Anaconda3\envs\torch\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Users\tangw\Anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\jyp\ICP-SHM-P1\DeepLabv3_torch\models\segmentation\deeplabv3.py", line 92, in forward
    res.append(conv(x))
  File "C:\Users\tangw\Anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\jyp\ICP-SHM-P1\DeepLabv3_torch\models\segmentation\deeplabv3.py", line 61, in forward
    x = super(ASPPPooling, self).forward(x)
  File "C:\Users\tangw\Anaconda3\envs\torch\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Users\tangw\Anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\tangw\Anaconda3\envs\torch\lib\site-packages\torch\nn\modules\batchnorm.py", line 131, in forward
    return F.batch_norm(
  File "C:\Users\tangw\Anaconda3\envs\torch\lib\site-packages\torch\nn\functional.py", line 2012, in batch_norm
    _verify_batch_size(input.size())
  File "C:\Users\tangw\Anaconda3\envs\torch\lib\site-packages\torch\nn\functional.py", line 1995, in _verify_batch_size
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])

**Comment by tangwentlw** [comment]
@bemoregt I got it! you refer to this post: https://discuss.pytorch.org/t/error-expected-more-than-1-value-per-channel-when-training/26274. 

"The error is most likely thrown during training and if the current batch only contains a single sample.
As you’ve explained this might happen, if the length of your Dataset is not dividable by the batch size without a remainder, which happens to be 1.
You could set drop_last=True in your DataLoader and run your code again."

**Comment by msminhas93** [comment]
> @bemoregt I got it! you refer to this post: https://discuss.pytorch.org/t/error-expected-more-than-1-value-per-channel-when-training/26274.
> 
> "The error is most likely thrown during training and if the current batch only contains a single sample.
> As you’ve explained this might happen, if the length of your Dataset is not dividable by the batch size without a remainder, which happens to be 1.
> You could set drop_last=True in your DataLoader and run your code again."

This precisely explains the error. Thank you @tangwentlw for sharing this with us

**Comment by GerardWalsh** [comment]
I encountered the same issue with changing the batch size to 2, which I did as a work around for running out of memory (6GB GTX1060). Another option is to use ResNet50 as a backbone - less model parameters, therefore less required memory, and might do better on a smaller dataset, again for the reason that there are less parameters to estimate.
